sudo: require
language: cpp
compiler: gcc
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ls -l
script: ./tests